# ===== APPLICATION NAME =====

spring.application.name=ecom

# ===== MYSQL CONNECTION =====

spring.datasource.url=jdbc:mysql://localhost:3306/ecom?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8

spring.datasource.username=root

spring.datasource.password=ZAYNEBKH1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / HIBERNATE =====

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.use_sql_comments=true

# ===== SERVER =====

server.port=8082

# ===== LOGGING =====

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.web=INFO

logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# ===== SWAGGER UI =====

springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.operationsSorter=method

springdoc.swagger-ui.tagsSorter=alpha

springdoc.show-actuator=true

# ===== DEVTOOLS =====

spring.devtools.restart.enabled=false

# ===== KEYCLOAK CONFIGURATION =====

# ===== KEYCLOAK CONFIGURATION =====

keycloak.auth-server-url=http://localhost:8180

keycloak.realm=rh-platform

keycloak.resource=rh-backend

keycloak.credentials.secret=1UTOVbJ7iput8lIBCo2PpNBOJJGo76DF

keycloak.use-resource-role-mappings=true

keycloak.bearer-only=true

keycloak.principal-attribute=preferred_username

keycloak.cors=true

# ===== SPRING SECURITY OAUTH2 =====

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083/realms/rh-platform