spring.application.name=ecom

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecom?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&sessionVariables=transaction_isolation='READ-COMMITTED'}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ZAYNEBKH1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

spring.main.lazy-initialization=true

server.port=${PORT:8080}
server.error.include-message=always
server.error.include-binding-errors=always

keycloak.auth-server-url=https://pfe-project-1-s20t.onrender.com
keycloak.realm=portail_rh
keycloak.resource=portail_rh_backend
keycloak.credentials.secret=iCUODsDl97yd4VukhmmniZGUuyN3a4qu
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true
keycloak.principal-attribute=preferred_username
keycloak.cors=true
keycloak.ssl-required=external
keycloak.confidential-port=0
keycloak.frontend-client-id=portail_rh_frontend

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://pfe-project-1-s20t.onrender.com/realms/portail_rh
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://pfe-project-1-s20t.onrender.com/realms/portail_rh/protocol/openid-connect/certs

keycloak.admin.server-url=https://pfe-project-1-s20t.onrender.com
keycloak.admin.realm=portail_rh
keycloak.admin.client-id=portail_rh_backend
keycloak.admin.client-secret=iCUODsDl97yd4VukhmmniZGUuyN3a4qu

keycloak.user.client-id=portail_rh_backend
keycloak.user.client-secret=iCUODsDl97yd4VukhmmniZGUuyN3a4qu

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

camunda.bpm.database.type=mysql
camunda.bpm.database.schema-update=true
camunda.bpm.database.skip-isolation-level-check=true
camunda.bpm.process-engine-name=default
camunda.bpm.history-level=full
camunda.bpm.auto-deployment-enabled=false
camunda.bpm.deployment-resource-pattern=classpath*:/bpmn/**/*.bpmn,classpath*:/bpmn/**/*.bpmn20.xml
camunda.bpm.spin.dataformat.json=jackson
camunda.bpm.spin.dataformat.xml=dom
camunda.bpm.generate-unique-process-engine-name=false
camunda.bpm.webapp.index-redirect-enabled=true
camunda.bpm.webapp.security.enabled=false
camunda.rest.url=https://pfe-project-6txv.onrender.com/engine-rest
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED

spring.security.method-security.enabled=true
camunda.bpm.identity-provider.keycloak.group-mapping.enabled=true
camunda.bpm.identity-provider.keycloak.group-mapping.role-prefix=

app.photo.storage.path=./uploads/photos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
file.upload-dir=./uploads

ai.recommendation.url=http://localhost:5000/recommend
ia.matching.url=http://localhost:8001/api/matching/analyze

logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO
logging.level.com.codeWithProject.ecom=INFO