FROM quay.io/keycloak/keycloak:26.6.0

ENV KC_DB=postgres

ENV KC_BOOTSTRAP_ADMIN_USERNAME=admin
ENV KC_BOOTSTRAP_ADMIN_PASSWORD=admin123456

ENV KC_CACHE=local
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT=false
ENV KC_PROXY_HEADERS=xforwarded

COPY ecom/keycloak/themes/ /opt/keycloak/themes/

RUN /opt/keycloak/bin/kc.sh build

CMD ["start"]