FROM quay.io/keycloak/keycloak:26.5.5

ENV KC_DB=mysql
ENV KC_DB_URL=jdbc:mysql://keycloak-db13d64237-emnarahmoune13-53c7.l.aivencloud.com:20867/defaultdb?sslMode=REQUIRED&allowPublicKeyRetrieval=true
ENV KC_DB_USERNAME=avnadmin
ENV KC_DB_PASSWORD=${KC_DB_PASSWORD}

ENV KC_BOOTSTRAP_ADMIN_USERNAME=admin
ENV KC_BOOTSTRAP_ADMIN_PASSWORD=admin123456

ENV KC_CACHE=local
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME=https://pfe-project-1-s20t.onrender.com
ENV KC_PROXY_HEADERS=xforwarded

RUN /opt/keycloak/bin/kc.sh build

COPY ecom/keycloak/themes/ /opt/keycloak/themes/

EXPOSE 8080

CMD ["start", "--http-enabled=true", "--http-port=8080", "--http-host=0.0.0.0", "--hostname=https://pfe-project-1-s20t.onrender.com", "--hostname-strict=false", "--proxy-headers=xforwarded"]